name: sdgai
channels:
  - pytorch
  - anaconda
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - pytorch
  - torchvision
  - geopandas
  - rasterio
  - shapely
  - matplotlib-scalebar
  - opencv
  - seaborn
  - contextily
