name: sdgai
channels:
  - pytorch
  - anaconda
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - torch
  - torchvision
  - geopandas
  - rasterio
  - shapely
  - cv2
  - pandas
  - seaborn
  - contextily
  - matplotlib
  - scipy
  - sklearn
